# permissions for end users to edit releaseupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releaseupgrade-editor-role
rules:
- apiGroups:
  - relup.lrascao.github.io
  resources:
  - releaseupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - relup.lrascao.github.io
  resources:
  - releaseupgrades/status
  verbs:
  - get
