# permissions for end users to view releaseupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releaseupgrade-viewer-role
rules:
- apiGroups:
  - relup.lrascao.github.io
  resources:
  - releaseupgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - relup.lrascao.github.io
  resources:
  - releaseupgrades/status
  verbs:
  - get
